name: CD

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
          registry-url: https://registry.npmjs.org/
      - name: build and deploy main
        run: |
          npm ci
          npm run build
          npm run dp:stg:e
        working-directory: ./main      
  nav:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
          registry-url: https://registry.npmjs.org/
      - name: build and deploy nav
        run: |
          npm ci
          npm run build
          npm run dp:stg:e
        working-directory: ./nav      
